[package]
name = "loggr"
version = "0.1.0"
authors = ["Gabriel Hooks <gabriel.i.hooks@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
color-eyre = "0.6.3"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
